name: 🐞 Bug report
description: Create a report to help us improve
title : "[Bug]: "
labels: "bug"
body:
- type: dropdown
  attributes:
    label: Variant
    description: What variant of the firmware are you using?
    multiple: false
    options:
      - ADC
      - USART
      - NUNCHUK
      - PPM
      - PWM
      - IBUS
      - HOVERCAR
      - TRANSPOTTER
      - SKATEBOARD
      - HOVERBOARD
  validations:
    required: true
- type: dropdown
  attributes:
    label: Control type
    description: What Control type are you using?
    multiple: false
    options:
      - Commutation
      - Sinusoidale
      - FOC
  validations:
    required: true    
- type: dropdown
  attributes:
    label: Control mode
    description: What Control mode are you using?
    multiple: false
    options:
      - Voltage
      - Speed
      - Torque
  validations:
    required: true    

- type: textarea
  attributes:
    label: Desciption
    description: Describe the bug and how we can reproduce it.
    placeholder: bla bla bla
  validations:
    required: true
